import { Booking } from "@/types/booking"

// Mock data cho booking management
export const mockBookingsData: Booking[] = [
    {
        bookingID: '1',
        tourID: '1',
        userID: '2',
        bookingDate: '2024-12-15',
        numAdults: 2,
        numChildren: 1,
        totalPrice: 15000000,
        paymentStatus: 'completed',
        bookingStatus: 'confirmed',
        specialRequests: 'Cần phòng không hút thuốc',
        createdAt: '2024-11-20T10:30:00',
        updatedAt: '2024-11-20T10:30:00',
        // Relations
        tourTitle: 'Du lịch Hạ Long - Hà Nội 3N2Đ',
        tourDestination: 'Hạ Long - Hà Nội',
        userName: 'Nguyễn Văn A',
        userEmail: 'nguyenvana@gmail.com',
        userPhone: '0987654321',
    },
    {
        bookingID: '2',
        tourID: '2',
        userID: '3',
        bookingDate: '2024-12-20',
        numAdults: 4,
        numChildren: 2,
        totalPrice: 32000000,
        paymentStatus: 'pending',
        bookingStatus: 'confirmed',
        specialRequests: 'Có người già đi cùng, cần hỗ trợ di chuyển',
        createdAt: '2024-11-22T14:15:00',
        updatedAt: '2024-11-22T14:15:00',
        tourTitle: 'Khám phá Đà Nẵng - Hội An 4N3Đ',
        tourDestination: 'Đà Nẵng - Hội An',
        userName: 'Trần Thị B',
        userEmail: 'tranthib@gmail.com',
        userPhone: '0912345678',
    },
    {
        bookingID: '3',
        tourID: '3',
        userID: '4',
        bookingDate: '2024-12-10',
        numAdults: 2,
        numChildren: 0,
        totalPrice: 12000000,
        paymentStatus: 'completed',
        bookingStatus: 'completed',
        specialRequests: '',
        createdAt: '2024-11-01T09:00:00',
        updatedAt: '2024-12-11T16:30:00',
        tourTitle: 'Phú Quốc - Thiên đường biển đảo 5N4Đ',
        tourDestination: 'Phú Quốc',
        userName: 'Lê Văn C',
        userEmail: 'levanc@gmail.com',
        userPhone: '0923456789',
    },
    {
        bookingID: '4',
        tourID: '1',
        userID: '5',
        bookingDate: '2024-12-25',
        numAdults: 3,
        numChildren: 1,
        totalPrice: 19500000,
        paymentStatus: 'failed',
        bookingStatus: 'cancelled',
        specialRequests: 'Thanh toán thất bại',
        createdAt: '2024-11-25T11:45:00',
        updatedAt: '2024-11-26T08:00:00',
        tourTitle: 'Du lịch Hạ Long - Hà Nội 3N2Đ',
        tourDestination: 'Hạ Long - Hà Nội',
        userName: 'Phạm Thị D',
        userEmail: 'phamthid@gmail.com',
        userPhone: '0934567890',
    },
    {
        bookingID: '5',
        tourID: '4',
        userID: '6',
        bookingDate: '2025-01-05',
        numAdults: 2,
        numChildren: 2,
        totalPrice: 18000000,
        paymentStatus: 'completed',
        bookingStatus: 'confirmed',
        specialRequests: 'Cần ghế ngồi gần nhau trên xe',
        createdAt: '2024-11-28T13:20:00',
        updatedAt: '2024-11-28T13:20:00',
        tourTitle: 'Sapa - Chinh phục Fansipan 3N2Đ',
        tourDestination: 'Sapa - Lào Cai',
        userName: 'Hoàng Văn E',
        userEmail: 'hoangvane@gmail.com',
        userPhone: '0945678901',
    },
    {
        bookingID: '6',
        tourID: '5',
        userID: '7',
        bookingDate: '2025-01-10',
        numAdults: 6,
        numChildren: 0,
        totalPrice: 36000000,
        paymentStatus: 'pending',
        bookingStatus: 'confirmed',
        specialRequests: 'Đoàn công ty, cần xuất hóa đơn VAT',
        createdAt: '2024-11-30T16:00:00',
        updatedAt: '2024-11-30T16:00:00',
        tourTitle: 'Nha Trang - Vinpearl Land 4N3Đ',
        tourDestination: 'Nha Trang',
        userName: 'Võ Thị F',
        userEmail: 'vothif@gmail.com',
        userPhone: '0956789012',
    },
    {
        bookingID: '7',
        tourID: '6',
        userID: '8',
        bookingDate: '2024-12-05',
        numAdults: 2,
        numChildren: 0,
        totalPrice: 14000000,
        paymentStatus: 'completed',
        bookingStatus: 'completed',
        specialRequests: '',
        createdAt: '2024-10-20T10:00:00',
        updatedAt: '2024-12-06T09:00:00',
        tourTitle: 'Đà Lạt - Thành phố ngàn hoa 3N2Đ',
        tourDestination: 'Đà Lạt',
        userName: 'Đỗ Văn G',
        userEmail: 'dovang@gmail.com',
        userPhone: '0967890123',
    },
    {
        bookingID: '8',
        tourID: '7',
        userID: '2',
        bookingDate: '2025-01-15',
        numAdults: 1,
        numChildren: 0,
        totalPrice: 8000000,
        paymentStatus: 'completed',
        bookingStatus: 'confirmed',
        specialRequests: 'Đi một mình, mong được sắp xếp roommate',
        createdAt: '2024-12-01T08:30:00',
        updatedAt: '2024-12-01T08:30:00',
        tourTitle: 'Hà Giang - Hành trình Cao nguyên đá 4N3Đ',
        tourDestination: 'Hà Giang',
        userName: 'Nguyễn Văn A',
        userEmail: 'nguyenvana@gmail.com',
        userPhone: '0987654321',
    },
]
